### ISSUE TITLE
Deployment to Digital Ocean

### ISSUE THREAD

**Issue by chrisdubya** [niceandserious/crafty-vagrant#19]
Have been banging my head against the wall with this one.  

I've set up a LAMP droplet on Digital Ocean and have basically been following [this script](http://deploybot.com/guides/deploy-craft-cms-to-digitalocean).  Which is essentially copying the craft and public folders to `/var/www/` (renaming all instances of public to html in order to play nice with Digital Ocean).  Except I keep getting 404s when trying to access `index.php` or `index.php/admin/install`.

I remember at N&S we would just push the entire app to mangrove and I think there was an apache conf to take care of the rest, but it's all a bit fuzzy now.

Do you have a recommended or proven ways of deploying on Digital Ocean or any other service for that matter?

Thanks!

**Comment by nickautomatic** [comment]
Hi Chris. Sorry, I don't have any experience of deploying Crafty on Digital Ocean, but it sounds like the issue is with having to move Craft's public directory to a non-standard location.

Crafty Vagrant just uses a totally standard Craft set-up, so should be fine on any Apache VirtualHost configured to use the `app/public` directory as the document root, and can be deployed exactly as per Craft's [installation guide](https://craftcms.com/docs/installing).

Moving Craft's public directory though is something I've never needed to do, I'm afraid. All I can suggest is that if you're getting a 404 when trying to access `index.php` then the problem is a server issue rather than a Craft (or Crafty Vagrant, for that matter) issue - most likely that your public directory isn't in the right location, I'd guess. One thing that caught my eye was that you said "renaming all instances of public", but you should probably only be renaming the one `public` folder, so I wonder if you've renamed something that didn't need renaming? Bear in mind that you probably only *need* to be uploading the `app/craft` and `app/public` folders from Crafty, and by the sound of it, the contents of `app/public` needs to go into `/html` and the `craft` folder needs to sit alongside that. Maybe try destroying your droplet and trying again step-by-step making sure everything is definitely in the right place.

Anyway, good luck.

**Comment by chrisdubya** [comment]
Figured it out, looks like with Digital Ocean you have to add the following directory statement to `/etc/apache2/sites-available/000-default.conf`: 

    <Directory /var/www/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>

I feel like we had to do something similar with Mangrove?  Might need to get my memory checked 🤔

Anyway, thanks!
