### ISSUE TITLE
Path to src/images in template files

### ISSUE THREAD

**Issue by wihodges** [niceandserious/crafty-vagrant#22]
This a probably a dumb question: what is the path to app/src/images? For instance, calling an image in _layout.twig, what would be the correct path?  {{ site.url }}/images/ does not seem to work.

**Comment by nickautomatic** [comment]
Ah, not at all. Nothing in app/src has a path - these are all source files that the Gulpfile does stuff with before copying them to the public directory. Images that are added to app/src/images are processed by the `gulp images` task. If you add the images while `gulp watch` is running, that should happen automatically. Otherwise, you'll need to run `gulp images` (or just `gulp` to run all build tasks) separately. `gulp images` makes sure all the images are optimally compressed, and then copies them to the public directory.

**Comment by wihodges** [comment]
Strange, so I received no errors while running gulp-watch, but once I ran
gulp-images seperately, I got a Enoent on optipng. So ran npm uninstall
gulp-imagemin, then updated the package.json imagemin to "gulp-imagemin":
"2.4.0" not "^2.4.0" . npm install gulp-imagemin.  Success and works now as
expected.

**Comment by nickautomatic** [comment]
Huh, that's strange. I've occasionally had problems in the past with some versions of optipng, so possibly they've released a version that is not entirely stable or something. Hmm, perhaps we should temporarily lock it to a fixed version... I'll have a think about that. Anyway, thanks for the info and glad you managed to get it working.

**Comment by wihodges** [comment]
Yea it seems my npm-modules are outta wack.

Another thing I realized is the need to run gulp-images anytime a new image
is placed in the src/image folder. Might be nice to reverse image process,
stick them into the public/images folder run gulp build and then compiles
and compresses everything getting it ready for rsync.

**Comment by nickautomatic** [comment]
@wihodges I had a look into this - since you shouldn't have to run `gulp images` every time - and it turned out that I'd semi-broken the image watch task when we switched from Grunt to Gulp a little while ago. Anyway, that should hopefully now be fixed, so that `gulp watch` catches any new images added to the `src/images` folder and processes them appropriately - ie. optimises them and copies them to public.

I've also tweaked it so that it runs all default tasks before watch, so if you've added any new images when watch wasn't running, those will get processed next time you run watch.
